#!/usr/bin/env bash
# vm-setup.sh
#
# One-command setup for the GPU VM.
# Installs Docker, NVIDIA Container Toolkit, clones the repo,
# writes a .env, and starts the VideoWorker + WanGP containers.
#
# The SocialMediaAPI runs on your LOCAL machine — not on this VM.
# The VM only needs the video worker and the AI model.
#
# ── How to use ────────────────────────────────────────────────────────────────
#
#   1. SSH into your VM
#   2. Paste and run the block below (fill in your real values first):
#
# export REPO_URL="https://github.com/your-username/sports-mono-repo.git"
# export MONGODB_CONNECTION_STRING="mongodb+srv://kampermanconor_db_user:YOUR_PASSWORD@cluster0.qcize5z.mongodb.net/SocialMediaDb?retryWrites=true&w=majority&appName=Cluster0"
# export R2_ACCOUNT_ID="21e609bb595ba48b08a0d100967c30de"
# export R2_ACCESS_KEY="your-r2-access-key"
# export R2_SECRET_KEY="your-r2-secret-key"
# export R2_BUCKET_NAME="social-media-assets"
# bash <(curl -fsSL https://raw.githubusercontent.com/your-username/sports-mono-repo/main/services/vm-setup.sh)
#
# ── Or if you already cloned the repo ─────────────────────────────────────────
#
# export MONGODB_CONNECTION_STRING="..."  # (same vars as above)
# bash /path/to/repo/services/vm-setup.sh

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
REPO_DIR="${REPO_DIR:-/workspace/sports-mono-repo}"
VIDEO_GENERATOR_TYPE="${VIDEO_GENERATOR_TYPE:-WanGP}"
WORKER_ID="${WORKER_ID:-worker-vm-01}"
WANGP_COMMIT="${WANGP_COMMIT:-main}"

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo -e "\n\033[1;32m[setup]\033[0m $*"; }
err()  { echo -e "\n\033[1;31m[error]\033[0m $*" >&2; exit 1; }
step() { echo -e "\033[1;34m  →\033[0m $*"; }

log "GPU Video Worker Setup"
echo "  This installs Docker, NVIDIA Container Toolkit, and starts"
echo "  the VideoWorker + WanGP generation containers."
echo "  The SocialMediaAPI is NOT installed here — run that locally."
echo ""

# ── Validate required vars ────────────────────────────────────────────────────
: "${MONGODB_CONNECTION_STRING:?Export MONGODB_CONNECTION_STRING before running}"
: "${R2_ACCOUNT_ID:?Export R2_ACCOUNT_ID before running}"
: "${R2_ACCESS_KEY:?Export R2_ACCESS_KEY before running}"
: "${R2_SECRET_KEY:?Export R2_SECRET_KEY before running}"
R2_BUCKET_NAME="${R2_BUCKET_NAME:-social-media-assets}"

# ── 1. System packages ────────────────────────────────────────────────────────
log "Updating system packages..."
apt-get update -qq
apt-get install -y -qq curl git

# ── 2. Docker ─────────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    log "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    usermod -aG docker "$USER" || true
    log "Docker installed"
else
    log "Docker already installed — skipping"
fi

# docker compose v2 (plugin)
if ! docker compose version &>/dev/null 2>&1; then
    log "Installing docker compose plugin..."
    apt-get install -y -qq docker-compose-plugin
fi

# ── 3. NVIDIA Container Toolkit ───────────────────────────────────────────────
if ! dpkg -l 2>/dev/null | grep -q nvidia-container-toolkit; then
    log "Installing NVIDIA Container Toolkit..."
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
        | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
        | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
        | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    apt-get update -qq
    apt-get install -y -qq nvidia-container-toolkit
    nvidia-ctk runtime configure --runtime=docker
    systemctl restart docker
    log "NVIDIA Container Toolkit installed"
else
    log "NVIDIA Container Toolkit already installed — skipping"
fi

# ── 4. Verify GPU ─────────────────────────────────────────────────────────────
log "Checking GPU..."
if ! nvidia-smi &>/dev/null; then
    err "nvidia-smi failed — make sure the NVIDIA driver is installed on this VM before running this script."
fi
nvidia-smi --query-gpu=name,memory.total --format=csv,noheader
log "GPU OK"

# ── 5. Clone or update repo ───────────────────────────────────────────────────
if [[ -d "$REPO_DIR/.git" ]]; then
    log "Repo already exists — pulling latest..."
    git -C "$REPO_DIR" pull --ff-only
else
    : "${REPO_URL:?Export REPO_URL (your GitHub repo URL) before running}"
    log "Cloning repo to $REPO_DIR..."
    mkdir -p "$(dirname "$REPO_DIR")"
    git clone "$REPO_URL" "$REPO_DIR"
fi

# ── 6. Write .env (VM only needs docker-compose vars) ─────────────────────────
log "Writing .env..."
cat > "$REPO_DIR/services/.env" <<EOF
# Generated by vm-setup.sh — do not commit
# VM only runs VideoWorker + WanGP. SocialMediaAPI runs on your local machine.

MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
R2_ACCESS_KEY=${R2_ACCESS_KEY}
R2_SECRET_KEY=${R2_SECRET_KEY}
R2_BUCKET_NAME=${R2_BUCKET_NAME}
VIDEO_GENERATOR_TYPE=${VIDEO_GENERATOR_TYPE}
WORKER_ID=${WORKER_ID}
WANGP_COMMIT=${WANGP_COMMIT}
EOF
chmod 600 "$REPO_DIR/services/.env"
log ".env written"

# ── 7. Create temp directory for video worker ─────────────────────────────────
mkdir -p /tmp/video-worker

# ── 8. Start the video stack ──────────────────────────────────────────────────
log "Building and starting containers..."
echo "  First run downloads WanGP and the LTX model weights (~10-20 GB)."
echo "  This can take a while — the worker won't process jobs until it's done."
echo ""

cd "$REPO_DIR/services"
docker compose -f docker-compose.video.yml pull 2>/dev/null || true
docker compose -f docker-compose.video.yml up --build -d

# ── 9. Summary ────────────────────────────────────────────────────────────────
VM_IP=$(curl -s --max-time 3 ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete                            ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Running on this VM:                                         ║"
echo "║    • VideoWorker  (polls MongoDB for jobs)                   ║"
echo "║    • WanGP        (AI video generation on GPU)               ║"
echo "║                                                              ║"
echo "║  Runs on your local machine:                                 ║"
echo "║    • SocialMediaAPI   dotnet run                             ║"
echo "║    • Angular frontend  npm start / nx serve                  ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Useful commands:                                            ║"
echo "║                                                              ║"
echo "║  Watch logs (model download progress):                       ║"
printf "║    docker compose -f %s/services/          \n" "$REPO_DIR"
echo "║        docker-compose.video.yml logs -f generation           ║"
echo "║                                                              ║"
echo "║  Check status:                                               ║"
printf "║    docker compose -f %s/services/          \n" "$REPO_DIR"
echo "║        docker-compose.video.yml ps                           ║"
echo "║                                                              ║"
echo "║  Update after git push:                                      ║"
printf "║    git -C %s pull              \n" "$REPO_DIR"
printf "║    docker compose -f %s/services/          \n" "$REPO_DIR"
echo "║        docker-compose.video.yml up --build -d                ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
log "Done! Submit a job from your local UI and watch it process."
